@echo off
echo Fixing Electron installation...
cd electron-app
echo Removing old modules...
rmdir /s /q node_modules
del package-lock.json
echo Installing dependencies...
call npm install
echo Installing latest Electron...
call npm install electron@latest --save-dev
echo Verifying Electron...
call npx electron --version
echo Done.
